dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
cache: pip

env:
  global:
    - AWS_DEFAULT_REGION: us-east-1

install:
  - pip install -r lambdacore/requirements.txt
  - pip install -r requirements-dev.txt

script:
  - pytest tests -vrf
  - pylint lambdacore
